//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingService.ProxyCacheService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/Cache.JCDecaux")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.InstructionType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Position))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Vehicle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.RouteSegment[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.RouteSegment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Position[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Station[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Stands))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Availabilities))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(global::RoutingService.ProxyCacheService.Station.StationStatus))]
    public partial class Station : object
    {
        
        private string AddressField;
        
        private bool BankingField;
        
        private bool BonusField;
        
        private bool ConnectedField;
        
        private string ContractNameField;
        
        private string LastUpdateField;
        
        private global::RoutingService.ProxyCacheService.Stands MainStandsField;
        
        private string NameField;
        
        private int NumberField;
        
        private bool OverflowField;
        
        private global::RoutingService.ProxyCacheService.Stands OverflowStandsField;
        
        private global::RoutingService.ProxyCacheService.Position PositionField;
        
        private object ShapeField;
        
        private global::RoutingService.ProxyCacheService.Station.StationStatus StatusField;
        
        private global::RoutingService.ProxyCacheService.Stands TotalStandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Banking
        {
            get
            {
                return this.BankingField;
            }
            set
            {
                this.BankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bonus
        {
            get
            {
                return this.BonusField;
            }
            set
            {
                this.BonusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Connected
        {
            get
            {
                return this.ConnectedField;
            }
            set
            {
                this.ConnectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractName
        {
            get
            {
                return this.ContractNameField;
            }
            set
            {
                this.ContractNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Stands MainStands
        {
            get
            {
                return this.MainStandsField;
            }
            set
            {
                this.MainStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Overflow
        {
            get
            {
                return this.OverflowField;
            }
            set
            {
                this.OverflowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Stands OverflowStands
        {
            get
            {
                return this.OverflowStandsField;
            }
            set
            {
                this.OverflowStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Position Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Shape
        {
            get
            {
                return this.ShapeField;
            }
            set
            {
                this.ShapeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Station.StationStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Stands TotalStands
        {
            get
            {
                return this.TotalStandsField;
            }
            set
            {
                this.TotalStandsField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Station.StationStatus", Namespace="http://schemas.datacontract.org/2004/07/Cache.JCDecaux")]
        public enum StationStatus : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CLOSED = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OPEN = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stands", Namespace="http://schemas.datacontract.org/2004/07/Cache.JCDecaux")]
    public partial class Stands : object
    {
        
        private global::RoutingService.ProxyCacheService.Availabilities AvailabilitiesField;
        
        private int CapacityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Availabilities Availabilities
        {
            get
            {
                return this.AvailabilitiesField;
            }
            set
            {
                this.AvailabilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity
        {
            get
            {
                return this.CapacityField;
            }
            set
            {
                this.CapacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/ORC.Models")]
    public partial class Position : object
    {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstructionType", Namespace="http://schemas.datacontract.org/2004/07/Cache.OpenRouteService")]
    public enum InstructionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Left = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Right = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SharpLeft = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SharpRight = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SlightLeft = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SlightRight = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Straight = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterRoundabout = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExitRoundabout = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTurn = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Goal = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Depart = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepLeft = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepRight = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeVehicle = 14,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/ORC.Models")]
    public enum Vehicle : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DrivingCar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DrivingHgv = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CyclingRegular = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CyclingRoad = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CyclingMountain = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CyclingElectric = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FootWalking = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FootHiking = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wheelchair = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteSegment", Namespace="http://schemas.datacontract.org/2004/07/ORC.Models")]
    public partial class RouteSegment : object
    {
        
        private double DistanceField;
        
        private double DurationField;
        
        private string InstructionTextField;
        
        private global::RoutingService.ProxyCacheService.InstructionType InstructionTypeField;
        
        private global::RoutingService.ProxyCacheService.Position[] PointsField;
        
        private string RoadNameField;
        
        private global::RoutingService.ProxyCacheService.Vehicle VehicleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstructionText
        {
            get
            {
                return this.InstructionTextField;
            }
            set
            {
                this.InstructionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.InstructionType InstructionType
        {
            get
            {
                return this.InstructionTypeField;
            }
            set
            {
                this.InstructionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Position[] Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoadName
        {
            get
            {
                return this.RoadNameField;
            }
            set
            {
                this.RoadNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public global::RoutingService.ProxyCacheService.Vehicle Vehicle
        {
            get
            {
                return this.VehicleField;
            }
            set
            {
                this.VehicleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Availabilities", Namespace="http://schemas.datacontract.org/2004/07/Cache.JCDecaux")]
    public partial class Availabilities : object
    {
        
        private int BikesField;
        
        private int ElectricalBikesField;
        
        private int ElectricalInternalBatteryBikesField;
        
        private int ElectricalRemovableBatteryBikesField;
        
        private int MechanicalBikesField;
        
        private int StandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bikes
        {
            get
            {
                return this.BikesField;
            }
            set
            {
                this.BikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElectricalBikes
        {
            get
            {
                return this.ElectricalBikesField;
            }
            set
            {
                this.ElectricalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElectricalInternalBatteryBikes
        {
            get
            {
                return this.ElectricalInternalBatteryBikesField;
            }
            set
            {
                this.ElectricalInternalBatteryBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElectricalRemovableBatteryBikes
        {
            get
            {
                return this.ElectricalRemovableBatteryBikesField;
            }
            set
            {
                this.ElectricalRemovableBatteryBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MechanicalBikes
        {
            get
            {
                return this.MechanicalBikesField;
            }
            set
            {
                this.MechanicalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stands
        {
            get
            {
                return this.StandsField;
            }
            set
            {
                this.StandsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="global::RoutingService.ProxyCacheService.IProxyCacheService")]
    public interface IProxyCacheService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStations", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsResponse")]
        System.Threading.Tasks.Task<global::RoutingService.ProxyCacheService.Station[]> GetStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsOfContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsOfContractResponse")]
        System.Threading.Tasks.Task<global::RoutingService.ProxyCacheService.Station[]> GetStationsOfContractAsync(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetRoute", ReplyAction="http://tempuri.org/IProxyCacheService/GetRouteResponse")]
        System.Threading.Tasks.Task<global::RoutingService.ProxyCacheService.RouteSegment[]> GetRouteAsync(global::RoutingService.ProxyCacheService.Position start, global::RoutingService.ProxyCacheService.Position end, global::RoutingService.ProxyCacheService.Vehicle vehicle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IProxyCacheServiceChannel : global::RoutingService.ProxyCacheService.IProxyCacheService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ProxyCacheServiceClient : System.ServiceModel.ClientBase<global::RoutingService.ProxyCacheService.IProxyCacheService>, global::RoutingService.ProxyCacheService.IProxyCacheService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProxyCacheServiceClient() : 
                base(ProxyCacheServiceClient.GetDefaultBinding(), ProxyCacheServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProxyCacheService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProxyCacheServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProxyCacheServiceClient.GetBindingForEndpoint(endpointConfiguration), ProxyCacheServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProxyCacheServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProxyCacheServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProxyCacheServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProxyCacheServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProxyCacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<global::RoutingService.ProxyCacheService.Station[]> GetStationsAsync()
        {
            return base.Channel.GetStationsAsync();
        }
        
        public System.Threading.Tasks.Task<global::RoutingService.ProxyCacheService.Station[]> GetStationsOfContractAsync(string contractName)
        {
            return base.Channel.GetStationsOfContractAsync(contractName);
        }
        
        public System.Threading.Tasks.Task<global::RoutingService.ProxyCacheService.RouteSegment[]> GetRouteAsync(global::RoutingService.ProxyCacheService.Position start, global::RoutingService.ProxyCacheService.Position end, global::RoutingService.ProxyCacheService.Vehicle vehicle)
        {
            return base.Channel.GetRouteAsync(start, end, vehicle);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProxyCacheService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProxyCacheService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5002/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProxyCacheServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProxyCacheService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProxyCacheServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProxyCacheService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProxyCacheService,
        }
    }
}
